version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - export TAG=$(echo "${CODEBUILD_BUILD_NUMBER}-${CODEBUILD_WEBHOOK_TRIGGER}-SNAPSHOT" | sed 's/pr\///' -)
  build:
    commands:
      - echo Build started
      - mvn clean install
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG .
      - echo Build complete
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG